window.PASSENGER_REVIEWS = {
  es: [
    { text: 'Excelente conductor, muy puntual y amable.', author: 'Lucía M.' },
    { text: 'El auto es súper cómodo y silencioso.', author: 'Carlos R.' },
    { text: 'Viaje impecable a Punta del Este.', author: 'Sofía B.' },
    { text: 'Mucho espacio para las valijas, genial.', author: 'Diego P.' },
    { text: 'Adrián maneja muy suave, casi no se siente.', author: 'Valentina G.' },
    { text: 'Llegamos al aeropuerto con tiempo de sobra.', author: 'Martín S.' },
    { text: 'El aire acondicionado perfecto en verano.', author: 'Camila F.' },
    { text: 'Puerta corrediza ideal para entrar cómodo.', author: 'Jorge L.' },
    { text: 'Auto eléctrico, cero olor y muy limpio.', author: 'Ana C.' },
    { text: 'Recomendado para traslados largos.', author: 'Pablo N.' },
    { text: 'Conductor profesional y muy educado.', author: 'Florencia D.' },
    { text: 'Viajé a Colonia, excelente experiencia.', author: 'Ricardo H.' },
    { text: 'Los asientos son amplios y cómodos.', author: 'Elena V.' },
    { text: 'Muy buena música y clima agradable.', author: 'Tomás A.' },
    { text: 'Puntualidad de diez, sin dudas.', author: 'Mariana K.' },
    { text: 'Ideal para ir al puerto con equipaje.', author: 'Federico J.' },
    { text: 'El viaje fue relajado y sin estrés.', author: 'Gabriela O.' },
    { text: 'Auto moderno, se nota el confort.', author: 'Hernán T.' },
    { text: 'Adrián conoce muy bien las rutas.', author: 'Paula E.' },
    { text: 'Silencioso de verdad, se puede descansar.', author: 'Ignacio W.' },
    { text: 'Perfecto para eventos y bodas.', author: 'Carolina I.' },
    { text: 'Muy limpio por dentro y por fuera.', author: 'Andrés Q.' },
    { text: 'Buen trato con niños y familia.', author: 'Laura Z.' },
    { text: 'Traslado corporativo impecable.', author: 'Roberto U.' },
    { text: 'Valijas grandes entraron sin problema.', author: 'Silvia Y.' },
    { text: 'Conducción segura y tranquila.', author: 'Emilio X.' },
    { text: 'Volvería a viajar sin pensarlo.', author: 'Natalia R.' },
    { text: 'Me encantó lo silencioso que es el NAT.', author: 'Bruno M.' },
    { text: 'Excelente para Uber y traslados privados.', author: 'Claudia P.' },
    { text: 'Servicio de primera, muy recomendable.', author: 'Oscar G.' }
  ],
  en: [
    { text: 'Excellent driver, very punctual and kind.', author: 'Lucia M.' },
    { text: 'The car is super comfortable and quiet.', author: 'Carlos R.' },
    { text: 'Flawless trip to Punta del Este.', author: 'Sofia B.' },
    { text: 'Plenty of room for luggage, great.', author: 'Diego P.' },
    { text: 'Adrian drives very smoothly, barely feel it.', author: 'Valentina G.' },
    { text: 'We reached the airport with time to spare.', author: 'Martin S.' },
    { text: 'Air conditioning was perfect in summer.', author: 'Camila F.' },
    { text: 'Sliding door makes getting in easy.', author: 'Jorge L.' },
    { text: 'Electric car, no smell and very clean.', author: 'Ana C.' },
    { text: 'Recommended for long transfers.', author: 'Pablo N.' },
    { text: 'Professional and polite driver.', author: 'Florencia D.' },
    { text: 'Trip to Colonia, excellent experience.', author: 'Ricardo H.' },
    { text: 'The seats are wide and comfortable.', author: 'Elena V.' },
    { text: 'Nice music and pleasant climate.', author: 'Tomas A.' },
    { text: 'Top punctuality, no doubt.', author: 'Mariana K.' },
    { text: 'Ideal for the port with luggage.', author: 'Federico J.' },
    { text: 'The ride was relaxed and stress-free.', author: 'Gabriela O.' },
    { text: 'Modern car, comfort shows.', author: 'Hernan T.' },
    { text: 'Adrian knows the routes very well.', author: 'Paula E.' },
    { text: 'Truly quiet, you can rest.', author: 'Ignacio W.' },
    { text: 'Perfect for events and weddings.', author: 'Carolina I.' },
    { text: 'Very clean inside and out.', author: 'Andres Q.' },
    { text: 'Great with kids and family.', author: 'Laura Z.' },
    { text: 'Impeccable corporate transfer.', author: 'Roberto U.' },
    { text: 'Large suitcases fit without issue.', author: 'Silvia Y.' },
    { text: 'Safe and calm driving.', author: 'Emilio X.' },
    { text: 'Would ride again without hesitation.', author: 'Natalia R.' },
    { text: 'Loved how quiet the NAT is.', author: 'Bruno M.' },
    { text: 'Excellent for Uber and private rides.', author: 'Claudia P.' },
    { text: 'First-class service, highly recommended.', author: 'Oscar G.' }
  ],
  pt: [
    { text: 'Excelente motorista, muito pontual e gentil.', author: 'Lucia M.' },
    { text: 'O carro é super confortável e silencioso.', author: 'Carlos R.' },
    { text: 'Viagem impecável para Punta del Este.', author: 'Sofia B.' },
    { text: 'Muito espaço para bagagens, ótimo.', author: 'Diego P.' },
    { text: 'Adrián dirige muito suave, quase não sente.', author: 'Valentina G.' },
    { text: 'Chegamos ao aeroporto com tempo de sobra.', author: 'Martin S.' },
    { text: 'Ar-condicionado perfeito no verão.', author: 'Camila F.' },
    { text: 'Porta corrediça ideal para entrar confortável.', author: 'Jorge L.' },
    { text: 'Carro elétrico, zero odor e muito limpo.', author: 'Ana C.' },
    { text: 'Recomendado para transfers longos.', author: 'Pablo N.' },
    { text: 'Motorista profissional e muito educado.', author: 'Florencia D.' },
    { text: 'Viajei a Colonia, excelente experiência.', author: 'Ricardo H.' },
    { text: 'Os assentos são amplos e confortáveis.', author: 'Elena V.' },
    { text: 'Boa música e clima agradável.', author: 'Tomas A.' },
    { text: 'Pontualidade nota dez, sem dúvida.', author: 'Mariana K.' },
    { text: 'Ideal para ir ao porto com bagagem.', author: 'Federico J.' },
    { text: 'A viagem foi relaxada e sem estresse.', author: 'Gabriela O.' },
    { text: 'Carro moderno, conforto se nota.', author: 'Hernan T.' },
    { text: 'Adrián conhece muito bem as rotas.', author: 'Paula E.' },
    { text: 'Silencioso de verdade, dá para descansar.', author: 'Ignacio W.' },
    { text: 'Perfeito para eventos e casamentos.', author: 'Carolina I.' },
    { text: 'Muito limpo por dentro e por fora.', author: 'Andres Q.' },
    { text: 'Ótimo trato com crianças e família.', author: 'Laura Z.' },
    { text: 'Transfer corporativo impecável.', author: 'Roberto U.' },
    { text: 'Malas grandes couberam sem problema.', author: 'Silvia Y.' },
    { text: 'Condução segura e tranquila.', author: 'Emilio X.' },
    { text: 'Voltaria a viajar sem pensar.', author: 'Natalia R.' },
    { text: 'Adorei o quão silencioso é o NAT.', author: 'Bruno M.' },
    { text: 'Excelente para Uber e transfers privados.', author: 'Claudia P.' },
    { text: 'Serviço de primeira, muito recomendável.', author: 'Oscar G.' }
  ]
};
